[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm --prefix server install",
  "npm --prefix client install --include=dev"
]

[phases.build]
cmds = [
  "npm --prefix client run build"
]

[start]
cmd = "node server/server.js"
